### ISSUE TITLE
Archiving an archive?

### ISSUE THREAD

**Issue by edsu** [harvard-lil/scoop#371]
I realize this isn't a common use case but I tried using scoop to archive a page in the Internet Archive Wayback Machine:

```
$ scoop https://web.archive.org/web/20051221165217if_/https://ldodds.com/writing/
```

You can find the WACZ here:

https://edsu-webarchives.s3.amazonaws.com/tmp/ldodds.wacz

I noticed that the screenshot looks fine:

![Screenshot 2024-10-18 at 11 37 24 AM](https://github.com/user-attachments/assets/b51f2f83-7a82-479e-aab2-b3e605ec1dc0)

But replay gets confused by some kind of recursive loop!

![Screenshot 2024-10-18 at 11 34 02 AM](https://github.com/user-attachments/assets/07347151-d61d-4e97-a42a-f4ae9a567fd8)

Is there any way around this?

**Comment by matteocargnelutti** [comment]
Hi @edsu 👋 ! I think this is known a playback issue with replayweb.page? Probably worth checking with folks at Webrecorder. Cheers!

**Comment by edsu** [comment]
@ikreymer just let me know that using the `id_` instead of `if_` view works ok! 

https://replayweb.page/?source=https%3A%2F%2Fedsu-webarchives.s3.amazonaws.com%2Ftmp%2Fldodds.wacz#view=pages&url=https%3A%2F%2Fweb.archive.org%2Fweb%2F20051221165217id_%2Fhttps%3A%2F%2Fldodds.com%2Fwriting%2F&ts=20241018194358

**Comment by rebeccacremona** [comment]
> @ikreymer just let me know that using the `id_` instead of `if_` view works ok!
> 
> https://replayweb.page/?source=https%3A%2F%2Fedsu-webarchives.s3.amazonaws.com%2Ftmp%2Fldodds.wacz#view=pages&url=https%3A%2F%2Fweb.archive.org%2Fweb%2F20051221165217id_%2Fhttps%3A%2F%2Fldodds.com%2Fwriting%2F&ts=20241018194358

@edsu For what it's worth, I get "Archived Page Not Found" when following that link.
![image](https://github.com/user-attachments/assets/2000fc70-0fcb-4af5-8681-d95b7f37f86a)

**Comment by edsu** [comment]
Weird, I don't see that ... 

<img width="1702" alt="Screenshot 2024-10-19 at 7 11 56 PM" src="https://github.com/user-attachments/assets/bc7b0ed3-403a-49d6-8d7d-2001d2f832ca">
